# Generated by Django 4.1.3 on 2024-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='name',
            field=models.IntegerField(),
        ),
    ]
