# Generated by Django 4.1.3 on 2024-07-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
