# Generated by Django 4.1.3 on 2024-08-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0002_alter_maintenance_maintenance_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenancePart',
        ),
    ]
