# Generated by Django 4.1.3 on 2024-07-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0002_alter_scooter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentransportapi.scooter')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.TextField()),
                ('part_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentransportapi.maintenance')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentransportapi.part')),
            ],
        ),
    ]
