# Generated by Django 4.1.3 on 2024-08-06 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0003_delete_maintenancepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentransportapi.maintenance')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentransportapi.part')),
            ],
        ),
    ]
