# Generated by Django 4.1.3 on 2024-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0005_ride_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
