# Generated by Django 4.1.3 on 2024-08-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greentransportapi', '0006_alter_ride_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='greentransportapi.user'),
        ),
    ]
